name: Continuous delivery
on:
  push:
    branches:
      - main
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/upload-artifact@v4
        with:
          name: myzip.zip
          path: C:/xampp/htdocs/treemap # or path/to/artifact
  
  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: myzip.zip
      - name: Display structure of downloaded files
        run: ls -R
