name: Lint
on:
  pull_request:
  push: 
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: firehed/lint-php-action@v1

  discord:
    run:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run Discord Webhook
          uses: bythope/discord-webhook-messages@v1.1.0
          with:
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            handler: 'push'
