name: Improve Commits with AI

on: 
  push:
    branches:
      - main

jobs:
  opencommit:
    name: Improve Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OpenCommit — improve commits with AI 
        uses: di-sukharev/opencommit@github-action-v1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
